- name: Implementacja serwera WWW
  hosts: servers
  vars_files: vars.yml
  tasks:
  - name: motd deploying
    template:
     src: issue.j2
     dest: /etc/issue
     owner: root
     group: root
     mode: 06444
