---
- name: Enable SELinux
  selinux:
    policy: targeted
    state: enforcing

- name: Polityka portu {{ port_www }}
  seport:
    ports: '{{ port_www }}'
    proto: tcp
    setype: http_port_t
    state: present

- name: KOntekst dla katalogu {{ katalog }}
  sefcontext:
    target: '{{ katalog }}(/.*)?'
    setype: httpd_sys_content_t
    state: present

- name: Apply new SELinux file context to filesystem
  command: restorecon -irv '{{ katalog }}'

