---
- name: Sprawdzam uprawnienia plikow
  hosts: poznan
  become: True
  vars:
    plik: /etc/hosts
  
  tasks:
    
    - name: Pobranie info o pliku
      stat:
        path: '{{ plik }}'
      register: spr_plik
    
    - name: Wyswietlenie info o pliku
      debug:
       var: spr_plik.stat.mode
    
    - name: Zmiana uprawnien do pliku
      file:
        path: '{{ plik }}'
        mode: 0600
      when: spr_plik.stat.mode == "0644"
