---
- name: Implementacja serwera WWW na serwerze gdansk
  hosts: gdansk
  tasks:
   - name: instalacja pakietu httpd
     yum:
       name: httpd
       state: latest
    
   - name: stworzenie pliku index.html
     copy:
       content: "Hello Apache\n"
       dest: /var/www/html/index.html
    
   - name: uruchomienie i autostart uslugi
     service:
       name: httpd
       state: started
       enabled: true

   - name: firewall dla portu 80/tcp
     firewalld:
       port: 80/tcp
       permanent: yes
       state: enabled
       immediate: true



- name: Implementacja serwera WWW na serwerze poznan
  hosts: poznan
  tasks:
    
   - name: instalacja pakietu httpd
     yum:
      name: httpd
      state: latest

   - name: stworzenie pliku index.html
     copy:
       content: "Hello Apache\n"
       dest: /var/www/html/index.html
     
   - name: uruchomienie i autostart uslugi
     service:
       name: httpd
       state: started
       enabled: true

   - name: firewall dla portu 80/tcp - WYLACZENIE
     firewalld:
       port: 80/tcp
       permanent: yes
       state: disabled
       immediate: true

- name: Test uslug
  hosts: localhost
  become: no
  tasks:
  - name: test polaczenia z gdynia
    uri:
     url: http://gdansk
     return_content: yes
     status_code: 200
  - name: test polaczenia z poznan
    uri:
     url: http://poznan
     return_content: yes
     status_code: 200
...
