---
- name: Implementacja serwera vsftpd na serwerze wroclaw
  hosts: wroclaw
  vars_files: vars.yml 
  tasks:
   - name: instalacja pakietu {{ ftp_package }}
     yum:
      name: "{{ ftp_package }}"
      state: latest
    
   - name: uruchomienie i autostart uslugi {{ ftp_service }}
     service:
      name: "{{ ftp_service }}" 
      state: started
      enabled: true
   - name: firewall dla uslugi {{ ftp_firewall }}
     firewalld:
      service: "{{ ftp_firewall }}"
      permanent: yes
      state: enabled
      immediate: true
