---
- name: Uruchom httpd na niestandardowym porcie
  hosts: servers
  vars:
   http_port: 12345
  tasks:

   - name: httpd - instalacja
     yum:
      name: httpd
      state: latest

   - name: httpd - autostart i start
     service:
      name: httpd
      state: started
      enabled: yes

   - name: Dodaj port {{ http_port }} do httpd.conf
     lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: "Listen {{ http_port }}"
     notify:
        - restart apache

   - name: Dodaj port {{ http_port }} konfiguracji SELinux
     seport:
      ports: "{{ http_port }}"
      proto: tcp
      setype: http_port_t
      state: present
     notify:
      - restart apache
  
   - name: Dodaj port {{ http_port }} do firewall
     firewalld:
      port: "{{ http_port }}/tcp"
      state: enabled
      permanent: yes
      immediate: true
      
  handlers:
   - name: restart apache
     service:
      name: httpd
      state: restarted
