---
- name: Implementacja serwera WWW
  hosts: servers
  tasks:
   - name: instalacja pakietu httpd
     yum:
       name: httpd
       state: latest
      
   - name: stworzenie pliku index.html
     copy:
       content: "Hello Apache\n"
       dest: /var/www/html/index.html

   - name: uruchomienie i autostart uslugi
     service:
       name: httpd
       state: started
       enabled: true

   - name: firewall dla portu 80/tcp
     firewalld:
       port: 80/tcp
       permanent: yes
       state: enabled
       immediate: true
...
