---
- name: Instalacja serwera vsftpd na serwerze poznan i kopia plików
  hosts: poznan
  vars:
    ftp_package: vsftpd
    ftp_firewall: ftp
    ftp_service: vsftpd
    pliki:
      - plik1
      - plik2
  tasks:
  - name: instalacja pakietu {{ ftp_package }}
    yum:
      name: "{{ ftp_package }}"
      state: latest
  - name: uruchomienie i autostart uslugi {{ ftp_service }}
    service:
      name: "{{ ftp_service }}"
      state: started
      enabled: true
  - name: firewall dla uslugi {{ ftp_firewall }}
    firewalld:
      service: "{{ ftp_firewall }}"
      permanent: yes
      state: enabled
      immediate: true
  - name: kopiowanie
    copy:
      src: /tmp/{{item}}
      dest: /var/ftp/pub/
    loop: '{{pliki}}'
  - block:
    - name: backup
      fetch:
        src: /etc/vsftpd/vsftpd.conf
        dest: tmp/backup/
    - name: zmien config
      lineinfile:
        path: /etc/vsftpd/vsftpd.conf
        state: present
        regexp: 'anonymous_enable=NO'
        line: 'anonymous_enable=YES'
      notify:
        - restart ftp
    rescue:
    - name: przywroc backup
      copy:
        src: /tmp/backup/vsftpd.conf
        dest: /etc/vsftpd/

 

  handlers:
  - name: restart ftp
    service:
      name: vsftpd
      state: restarted
