---
- name: Implementacja serwera vsftpd na serwerze poznan
  hosts: poznan
  vars:
   ftp_package: vsftpd
   ftp_firewall: ftp
   ftp_service: vsftpd
  tasks:

    - name: instalacja pakietu {{ ftp_package }}
      yum:
       name: "{{ ftp_package }}"
       state: latest

    - name: backup konifga.
      fetch:
        src: /etc/vsftpd/vsftpd.conf
        dest: /home/student/backup
    
    - name: uruchomienie i autostart uslugi {{ ftp_service }}
      service:
       name: "{{ ftp_service }}"
       state: started
       enabled: true
    
    - name: firewall dla uslugi {{ ftp_firewall }}
      firewalld:
       service: "{{ ftp_firewall }}"
       permanent: yes
       state: enabled
       immediate: true

    - name: kopiowanie plików
      copy:
       content: 'zawartosc pliku {{ item }}'
       dest: '/var/ftp/pub/{{ item }}'
      loop:
        - plik1
        - plik2

    - block:
        - name: konfig change
          lineinfile:
            regexp: 'anonymous_enable == NO'
            line: 'anonymous_enable == YES'
        - name: uruchomienie handlersa
          meta: flush_handlers

      rescue:
        - name: recovery config
          fetch: 
            src: /home/student/backup/poznan/etc/vsftpd/vsftpd.conf
            dest: /etc/vsftpd/vsftpd.conf
  handlers:
    - name: Restart uslugi
      systemd:
        name: "{{ ftp_package }}"
        state: restarted

